Repository YaleSpinup/ec2-api, pull requests merged in 2023-10, with the labels that each got.

#45 Add route for getting subnet details
  api/handlers_subnets.go
  api/routes.go
  api/types.go
  ec2/subnets.go
  ec2/subnets_test.go
Labels: enhancement

#46 Add dependabot
  .github/dependabot.yml
Labels: enhancement

#52 Updated go version, packages, and deco
  .github/workflows/test.yaml
  docker/Dockerfile
  docker/Dockerfile.local
  go.mod
  go.sum
Labels: enhancement, dependencies

#54 Update Instance List to add state and name
  ec2/instances.go
Labels: ready for review
